config/routes.rb
Rails.application.routes.draw do

  root 'pages#welcome'
  devise_for :users, controllers: { registrations: "registrations" }
  get 'pages/index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
      # redirect_to root_path if ! current_user
      @users = User.all
  end

  def welcome
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LarsDisplay</title>
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1"> -->
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.bundle.min.js">
  </head>

  <nav class="navbar navbar-expand-md navbar-light fixed-top">
    <div class="container">
        <a class="navbar-brand" href="/">
            Home
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">


            <% if current_user %>
            <li>
                <a class="nav-link nav-item"  <%= link_to "Sign out", destroy_user_session_path, method: :delete %></a>
            </li>
            <% else %>
            <li>
                <a class="nav-link nav-item" <%= link_to "Register", new_user_registration_path %>﻿﻿</a>
            </li>

            <li>
                <a class="nav-link nav-item" <%= link_to "Login", new_user_session_path %>﻿﻿</a>
            </li>

            <% end %>

            <!-- <li>
                <a class="nav-link nav-item"  <%= link_to 'Pages#index', pages_index_path %></a>
            </li> -->

            </ul>
        </div>
    </div>
</nav>

  <body>

    <div class="container py-5">

<% if  notice || alert %>
    <p class="notice"><%= notice %></p>
    <% elsif %>
        <p class="alert"><%= alert %></p>
<% end %>
        <%= yield %>
    </div>

  </body>
</html>

app/views/pages/index.html.erb
<!-- <h1>Pages#index</h1> -->
<section class="jumbotron text-center">

    <h1 class="jumbotron-heading">View Users</h1>
    <%= link_to 'Sign Up', new_user_registration_path, class:"btn btn-primary" %>
<hr>

<h5 class="jumbotron-heading">
    <%= @users.count %>
   <%=  "User".pluralize(@users.count)%>.
   <hr>
</h5>

    <div class="container">
        <p class="text-muted">
            <% @users.each do |user| %>

                <h1> <%= user.name %> </h1>
                <%= user.email %>
                <hr>
            <% end %>
        </p>
    </div>

</section>

app/views/pages/welcome.html.erb
<section class="jumbotron text-center">

<% if current_user %>
    <h1 class="jumbotron-heading">Welcome <%= current_user.name %></h1>
<% else %>
    <h1 class="jumbotron-heading">Welcome</h1>
<% end %>

    <div class="container">
        <br>

        <a>
            <%= link_to 'View Users', pages_index_path, class:"btn btn-lg btn-success btn-block" %>
        </a>

        <br>
        <p class="text-muted">
        Lorem ipsum dolor sit amet, consectetur adipisicing elit. Asperiores sapiente voluptatibus sed hic commodi repellendus dolorem soluta sint. Maxime ratione voluptatum voluptate nemo vitae minima magni tenetur aliquam illum sint cum rem, accusamus voluptates ea quod molestias enim numquam aut adipisci possimus quia porro necessitatibus. Fugit aliquam culpa exercitationem placeat.</p>

        <% if current_user %>
        <%= link_to "Sign out", destroy_user_session_path, method: :delete, class:"btn btn-danger btn-lg" %>
        <% else %>
            <%= link_to 'Register', new_user_registration_path, class:"btn btn-outline-primary my-2" %>
            <%= link_to 'Login', new_user_session_path, class:"btn btn-outline-success my-2" %>
        <% end %>

    </div>

</section>